{% set name = "datatoolbox" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datatoolbox-{{ version }}.tar.gz
  sha256: 1b1dbb3af9be31246526ab1d6030edf5c1bf1df0aa11beaa5cb01a0205cd619e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - appdirs
    - deprecated
    - fuzzywuzzy
    - gitpython
    - networkx >=2.4.0
    - matplotlib-base
    - numpy
    - openpyxl
    - openscm-units >0.5
    - pandas >=1.1.0
    - pandas-indexing
    - pint >=0.11
    - pint-xarray
    - pyam >=1.4.0
    - pyarrow
    - pycountry
    - python >=3.6
    - python-docx
    - tabulate
    - treelib
    - tqdm
    - xarray
    - xlsxwriter

test:
  imports:
    - datatoolbox
  commands:
    - pip check
  requires:
    - pip
    - git

about:
  home: https://gitlab.com/climateanalytics/datatoolbox
  summary: The Python Data Toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - coroa
    - geiges
