{% set name = "datatoolbox" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datatoolbox-{{ version }}.tar.gz
  sha256: fd561ab7de7a5af34f60624bdb15991a653d6e85787e04966651ad23ffb1be91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - appdirs
    - deprecated
    - fuzzywuzzy
    - gitpython
    - networkx >=2.4.0
    - openpyxl
    - openscm-units
    - pandas >=1.1.0
    - pint
    - pint-xarray
    - pyam >=1.4.0
    - pycountry
    - python >=3.6
    - python-docx
    - tabulate
    - tqdm
    - xarray

test:
  imports:
    - datatoolbox
  commands:
    - pip check
  requires:
    - pip
    - git

about:
  home: https://gitlab.com/climateanalytics/datatoolbox
  summary: The Python Data Toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - coroa
    - geiges
