{% set name = "datatoolbox" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datatoolbox-{{ version }}.tar.gz
  sha256: 0bd3d6628c7f8fa233939ce8c3f7b7d146cf5fc9a813900aadadc903804fb5b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - appdirs
    - deprecated
    - fuzzywuzzy
    - gitpython
    - ipython
    - matplotlib-base
    - networkx >=2.4
    - numpy
    - openpyxl
    - openscm-units >0.5
    - pandas >=2.0.0
    - pandas-indexing
    - pint >=0.11
    - pint-xarray
    - pyam >=2.2.0
    - pyarrow
    - pycountry
    - python >=3.6
    - python-calamine
    - python-docx
    - recommonmark
    - tabulate
    - treelib
    - tqdm
    - xarray >=2024.9
    - xlsxwriter

test:
  imports:
    - datatoolbox
  commands:
    - pip check
  requires:
    - pip
    - git

about:
  home: https://gitlab.com/climateanalytics/datatoolbox
  summary: The Python Data Toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - coroa
    - geiges
