{% set name = "datatoolbox" %}
{% set version = "0.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datatoolbox-{{ version }}.tar.gz
  sha256: 11f1529f2fc0fa49d50452e9541bfd87d21f8d5ee1eb146b42901447c83a0ed1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - appdirs
    - beautifulsoup4
    - deprecated
    - fuzzywuzzy
    - gitpython
    - itsdangerous
    - networkx >=2.4.0
    - openpyxl
    - openscm-units >0.5
    - pandas >=1.1.0
    - pint >=0.11
    - pint-xarray
    - pyam >=1.4.0
    - pycountry
    - pyarrow
    - python >=3.6
    - python-docx
    - ratelimit
    - tabulate
    - tqdm
    - xarray

test:
  imports:
    - datatoolbox
  commands:
    - pip check
  requires:
    - pip
    - git

about:
  home: https://gitlab.com/climateanalytics/datatoolbox
  summary: The Python Data Toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - coroa
    - geiges
